%% Last Edit 26/04/2017
%% Creates the Symbolic Model of the robot taking the files generated by the Mathematica Routine

%gives back the symbolic matrix "Wi" 

g = 9.81;

global Wi
global s

% Create Symbolic State Variables
syms q1 q2 qd1 qd2 qdd1 qdd2

% Load Parameters Vector (Sym)
coeff

% Load Dynamic Model (Sym)
Y

%% Deletes null columns of W and saves their indexes in order to delete the correspondent parameter
Wi = W;
s = all( isAlways(Wi==0) ,1);
Wi(:,s) = [];   
%% CHECK for residual null col.s
for i =  1:size(Wi,2)
    check = 0;
    if isequal(sym([0;0]), Wi(:,i))
        check = 1;
        break;
    end
end
if check
    error('Ooops! Something went wrong while creating the symbolic dynamic model');
else
    disp('CHECK: Ok!');
end  
%% Delete the corresponding elements of the coeff. vector
gamma(s) = [];
%%
clear W1i W2i W3i W4i W5i W6i i x g C2 C23 C3 C4 C5 C6 S2 S3 S23 S4 S5 S6 ...
      q1 q2 q3 q4 q5 q6 qd1 qd2 qd3 qd4 qd5 qd6 qdd1 qdd2 qdd3 qdd4 qdd5 qdd6 ...
      b1 b2 b3 b4 b5 b6 f1 f2 f3 f4 f5 f6 m1 m2 m3 m4 m5 m6 mr1x mr1y mr1z  ...
      mr2x mr2y mr2z mr3x mr3y mr3z mr4x mr4y mr4z mr5x mr5y mr5z mr6x mr6y  ...
      mr6z I1xx I1yy I1zz I1xy I1xz I1yz I2xx I2yy I2zz I2xy I2xz I2yz I3xx  ...
      I3yy I3zz I3xy I3xz I3yz I4xx I4yy I4zz I4xy I4xz I4yz I5xx I5yy I5zz ...
      I5xy I5xz I5yz I6xx I6yy I6zz I6xy I6xz I6yz
   